### ISSUE TITLE
getAllBOPs returns varying results

### ISSUE THREAD

**Issue by gianlucaschoefer** [coinop-logan/toastycoin#1]
The getAllBOPs.js from getAllBOPs.html returns varying results for created contracts on Mainnet. Something seems to be off with the events.

On Ropsten no contracts are returned.

**Comment by coinop-logan** [comment]
I set a repeating 1-second interval for the following function:

```
function checkForNewBOPs() {
    event = BOPFactory.contractInstance.NewBOP({}, {"fromBlock":3000000});//NewBOP is an event, not a method; it returns an event object.
    event.get(onNewBOP);
}
```

~~On a given load of the page, event.get repeatedly passes the same set of BOPs to onNewBOP; it seems to be all it can find. But when I reload the page, it could be a different set.~~ See next comment

**Comment by coinop-logan** [comment]
The filter will return one set of BOPs for anywhere between a few seconds and a minute, then randomly switch to returning another set. It's bizarre.

This is the result of logging the length of the returned event list every second.

![image](https://user-images.githubusercontent.com/22788901/29637214-eca92448-87ff-11e7-9c2b-c5087a65ca76.png)

**Comment by coinop-logan** [comment]
20 seconds, 62 seconds, 5 seconds, 58 seconds... Almost seems like Ethereum block times.

**Comment by coinop-logan** [comment]
Indeed, I've verified that when a new block comes out, it starts returning a different set of BOPs.

I've also found that it always returns the earliest BOPs, and when it doesn't return all 6, it's the latest BOPs in the list that get truncated.

**Comment by gianlucaschoefer** [comment]
This issue is resolved, when specifying the earliest block also "fromBlock" for the filtering of events, the block when the BOPFactory was created should be used, to decrease the parsing time, which ultimatly created the problems.
